name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest code on PythonAnywhere
        run: |
          curl -s -X POST \
            --data-urlencode "command=cd /home/${{ secrets.PA_USERNAME }}/E-com && git pull origin main" \
            -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/consoles/

      - name: Reload Web App
        run: |
          curl -s -X POST \
            -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/${{ secrets.PA_USERNAME }}.pythonanywhere.com/reload/
