name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest code on PythonAnywhere
        run: |
          curl -s -X POST \
            --data-urlencode "command=cd /home/ecommercetest/E-com && git pull origin main" \
            -H "Authorization: Token 8d8d9d2d1f59905bee45d383687831502c1763d4" \
            https://www.pythonanywhere.com/api/v0/user/8d8d9d2d1f59905bee45d383687831502c1763d4/consoles/

      - name: Reload Web App
        run: |
          curl -s -X POST \
            -H "Authorization: Token 8d8d9d2d1f59905bee45d383687831502c1763d4" \
            https://www.pythonanywhere.com/api/v0/user/ecommercetest/webapps/ecommercetest.pythonanywhere.com/reload/
